slogan: "Enjoy Eating & Creating"

menu:
  - title: About
    url: about
    intro: "About myself"
  - title: Resume
    url: resume
    intro: "My Resume"

links:
  - title: Freemind
    url: https://github.com/wzpan/hexo-theme-freemind
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: BOOTSTRA.386
    url: https://github.com/kristopolous/BOOTSTRA.386
    intro: "BOOTSTRA.386's Github repository."
    icon: "fa fa-github"
  - title: Freemind.386
    url: https://github.com/blackshow/hexo-theme-freemind.386
    intro: "Freemind.386's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/VikingWarlock
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My Twitter"
    url: https://twitter.com/VKWK_Viking
    intro: "My Twitter account"
    icon: "fa fa-twitter"
  - title: "Blog 1"
    url: http://vkwk.space
    intro: "My blog in China"
    icon: "fa fa-blog"
  - title: "Blog 2"
    url: http://vikingwarlock.github.io
    intro: "blog on github"
    icon: "fa fa-github"
  - title: "Peng Zhihui's"
    url: "http://pengzhihui.xyz"
    icon: "fa fa-blog"
  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: false
  siteid: 
baidu_tongji:
  enable: true
  siteid: e7b30175bed2ad5160ee5a9e2fc67e23

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
